name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight, adjust as needed

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.6.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: Configure AWS Credentials Using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::992382545225:role/Terraform_cicd_oidc
        role-session-name: GitHubActions
        aws-region: us-west-2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.6.0'

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform apply -auto-approve tfplan-destroy